services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - my_media:/files/media
    command: >
      sh -c "alembic upgrade head &&
            python3 -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
  redis:
    image: redis
    ports:
      - "6379:6379"
  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A celery_app worker --pool=solo --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - app
  flower:
    container_name: flower
    build: .
    command: /bin/sh -c "sleep 10 && celery -A celery_app flower --port=5555"
    ports:
      - 5556:5555
    depends_on:
      - app
      - redis
      - celery_worker
    env_file:
      - .env
volumes:
  my_media:
