"""Add is_blocked field to comments

Revision ID: 20450b6102ad
Revises: 6aa205626b58
Create Date: 2024-10-20 17:07:10.188589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20450b6102ad'
down_revision: Union[str, None] = '6aa205626b58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'is_blocked')
    # ### end Alembic commands ###
